### ISSUE TITLE
Issue with finishedCallback

### ISSUE THREAD

**Issue by SiENcE** [kikito/love-loader#8]
I get different results when the finishedCallback is called..

Sometimes I get this in the console.

```
first tween finished
image   table: 0x02945188       left-hand-climber-hi
second tween finished
```

and sometimes this:

```
first tween finished
image   table: 0x02945188       left-hand-climber-hi
second tween finished
second tween finished
```

Testprogram:
https://www.love2d.org/forums/download/file.php?id=9951

https://www.love2d.org/forums/viewtopic.php?f=5&t=77904&p=168404#p168318

https://www.love2d.org/forums/viewtopic.php?f=5&t=77904&p=168404#p168404

**Comment by kikito** [comment]
Hi, I have marked this project as deprecated and will close all open issues. Thanks for taking the time to report this.
